# Generated by Django 4.0.1 on 2022-01-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210131_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='title',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedIn',
            field=models.URLField(blank=True, primary_key=True, serialize=False),
        ),
    ]
