# Generated by Django 4.0.1 on 2022-01-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_agenda_id_remove_member_id_alter_agenda_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='firstName',
            field=models.CharField(blank=True, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedIn',
            field=models.URLField(blank=True),
        ),
    ]
