# Generated by Django 4.0.1 on 2022-01-11 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_member_firstname_alter_member_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='member',
            name='linkedIn',
        ),
    ]
