# Generated by Django 4.0.1 on 2022-01-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_member_instagram_remove_member_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedIn',
            field=models.URLField(blank=True),
        ),
    ]
