# Generated by Django 4.0.1 on 2022-01-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20210312_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='', max_length=2000000000, primary_key=True, serialize=False),
        ),
    ]
