# Generated by Django 4.0.1 on 2022-01-11 17:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210305_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='topicPref4',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='topicPref5',
        ),
        migrations.AddField(
            model_name='delegate',
            name='registeredBy',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='delegate',
            name='team',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='delegate',
            name='timeRegistered',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='topicPref1',
            field=models.CharField(choices=[('CLIMATE ACTION', 'CLIMATE ACTION'), ('FINANCIAL INDEPENDENCE OF WOMEN', 'FINANCIAL INDEPENDENCE OF WOMEN'), ('RURAL ILLITERACY AND UNEMPLOYMENT', 'RURAL ILLITERACY AND UNEMPLOYMENT'), ('YOUTH PRIVACY AND SOCIAL MEDIA', 'YOUTH PRIVACY AND SOCIAL MEDIA'), ('ZERO HUNGER', 'ZERO HUNGER')], default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='topicPref2',
            field=models.CharField(choices=[('CLIMATE ACTION', 'CLIMATE ACTION'), ('FINANCIAL INDEPENDENCE OF WOMEN', 'FINANCIAL INDEPENDENCE OF WOMEN'), ('RURAL ILLITERACY AND UNEMPLOYMENT', 'RURAL ILLITERACY AND UNEMPLOYMENT'), ('YOUTH PRIVACY AND SOCIAL MEDIA', 'YOUTH PRIVACY AND SOCIAL MEDIA'), ('ZERO HUNGER', 'ZERO HUNGER')], default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='topicPref3',
            field=models.CharField(choices=[('CLIMATE ACTION', 'CLIMATE ACTION'), ('FINANCIAL INDEPENDENCE OF WOMEN', 'FINANCIAL INDEPENDENCE OF WOMEN'), ('RURAL ILLITERACY AND UNEMPLOYMENT', 'RURAL ILLITERACY AND UNEMPLOYMENT'), ('YOUTH PRIVACY AND SOCIAL MEDIA', 'YOUTH PRIVACY AND SOCIAL MEDIA'), ('ZERO HUNGER', 'ZERO HUNGER')], default=None, max_length=2000),
        ),
    ]
