# Generated by Django 4.0.1 on 2022-01-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_delegate_id_remove_delegate_topicpref4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='counter',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='delegate',
            name='id',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
