# Generated by Django 4.0.1 on 2022-02-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_delegate_tnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='Paid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
