# Generated by Django 4.0.1 on 2022-02-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_delegate_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delegate',
            old_name='city',
            new_name='pastexp',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='address',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='age',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='courseName',
        ),
        migrations.RemoveField(
            model_name='delegate',
            name='yearGrad',
        ),
        migrations.AddField(
            model_name='delegate',
            name='altphoneNumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='delegate',
            name='dob',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='delegate',
            name='mumbai',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='delegate',
            name='teamyn',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non binary', 'Non binary'), ('Prefer not to Disclose', 'Prefer not to Disclose')], default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='topicPref1',
            field=models.CharField(choices=[('Affordable and Clean Energy', 'Affordable and Clean Energy'), ('Rural Healthcare', 'Rural Healthcare'), ('Sustainability of Consumer Goods', 'Sustainability of Consumer Goods'), ('Women`s Safety and Vigilance', 'Women`s Safety and Vigilance')], default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='topicPref2',
            field=models.CharField(choices=[('Affordable and Clean Energy', 'Affordable and Clean Energy'), ('Rural Healthcare', 'Rural Healthcare'), ('Sustainability of Consumer Goods', 'Sustainability of Consumer Goods'), ('Women`s Safety and Vigilance', 'Women`s Safety and Vigilance')], default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='delegate',
            name='topicPref3',
            field=models.CharField(choices=[('Affordable and Clean Energy', 'Affordable and Clean Energy'), ('Rural Healthcare', 'Rural Healthcare'), ('Sustainability of Consumer Goods', 'Sustainability of Consumer Goods'), ('Women`s Safety and Vigilance', 'Women`s Safety and Vigilance')], default=None, max_length=2000),
        ),
    ]
